name: Belaire
favicon: null
layout_spectrum: 0.9789107635151595
typography_spectrum: 0.6000076457858086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#254da5'
    - '#5c97d3'
    - '#d7def1'
    - '#cdae00'
    - '#7c4b00'
  brandStrength: 0.18446530331857502
  lightness: 0.868862486910075
  saturation: 0.560424736700952
  rhythmicContrast: 0.6058916870970279
purpose: []
